language: node_js
node_js:
  - '10'

stages:
  - build
  - test

jobs:
  include:
    - stage: build
      script: npm run build

    - stage: test
      script: npm run test

before_script:
  - cd assertly-oss-api
