language: node_js
node_js:
- 10
before_install:
- cd api
install: 
- npm install
- npm run build
before_deploy:
- cd ../
deploy:
  provider: npm
  email: zealotsd@gmail.com
  api_key:
    secure: ON0DP7Zyt3GaqXoXggFY9TmjDf6iHSxMJl+kTPgWZ3XTeI52U+FFzOg0acczIM5sgz3WhJ272r/oNJt34QlbyEfQgpalGbGa+x0kVDBYtoOa2l2J+vMSMUWczv66YED60n8Axr2+cSWnOg2Tui6gCW1ECYASscC5Jmy5sTsFAjsk8BLAC7wxELlIwNjL9Mz1gQrGVb0ECR5diQJgPoJ9hJu29LGmR+HQgjAfU1G68fS3weMFKOX/sms8Br9eCDtXn6hy5VdFsQOMD060mIGBIcDoHNOS0ywyiYEpD2N9rBT4eAeuii0l0CZO1T2jq0vfGuays8i/TvyYmPKMe1yrXRP+BFwKCxDuABXZSOz+PPQoppXTRftHgII82g6Ks8rqPlEgaeIr5/YgmGE+qXpWjvGsXlsw7/yhP4RGqI9HRjmLfgw5j4fZUKwlg0h8ufZkQS2ndZ2VHgxcEpmwjkcvgXzgn7fyPAuuk1Z5OqD1vUT7t2lD8acW53Cp9ru85uKZ1SPu+qWi8hYu7xbt80wRhRVNCPJJUs/yCnhdcyIunwWJb7MmjvkNxLiVj0BKGi6og6AjeV2KmrZOPADlLhZqs0U6IvvvTKbPvYGslF/fpJidgjtJpjmDjL4R0UqMjeGavei0aNrQ1V8jKF+pSXdp8VyhPXPRQovdSQI80e+829s=
